In [23]:
import pandas as pd
import numpy as np
import re
import string
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Data Loading

In [13]:
df = pd.read_csv(r'C:\Users\hp\OneDrive\Documents\Desktop\fake news detection\Data\WELFake_Dataset.csv')
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [14]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [15]:
df.head()

,title,text,label
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,NaN,Did they post their votes for Hillary already?,1
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   71576 non-null  object
 1   text    72095 non-null  object
 2   label   72134 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.7+ MB

In [17]:
df['label'].value_counts()

label
1    37106
0    35028
Name: count, dtype: int64

# Removing Null Values

In [18]:
df.isnull().sum()

title    558
text      39
label      0
dtype: int64

In [19]:
df.dropna(inplace=True)

In [20]:
df.isnull().sum()

title    0
text     0
label    0
dtype: int64

# Merging Title and Text

In [21]:
df['content'] = df['title'] + " " + df['text']
df = df[['content', 'label']]
df.head()

                                             content  label
0  LAW ENFORCEMENT ON HIGH ALERT Following Threat...      1
2  UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...      1
3  Bobby Jindal, raised Hindu, uses story of Chri...      0
4  SATAN 2: Russia unvelis an image of its terrif...      1
5  About Time! Christian Group Sues Amazon and SP...      1

# Cleaning The Text

In [28]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [29]:
def clean_text(text):
    text = re.sub(r'http\S+',"",text)
    text = re.sub(r'[^a-zA-Z\s]',"",text)
    text = text.lower()
    text = text.translate(str.maketrans('', '', string.punctuation))
    words = text.split()
    words =[lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    return " ".join(words)

In [30]:
df['clean_content'] = df['content'].apply(clean_text)
df.head()

,content,label,clean_content
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,1,law enforcement high alert following threat co...
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,1,unbelievable obamas attorney general say charl...
3,"Bobby Jindal, raised Hindu, uses story of Chri...",0,bobby jindal raised hindu us story christian c...
4,SATAN 2: Russia unvelis an image of its terrif...,1,satan russia unvelis image terrifying new supe...
5,About Time! Christian Group Sues Amazon and SP...,1,time christian group sue amazon splc designati...

In [31]:
df = df[['clean_content', 'label']]
df.head()

                                       clean_content  label
0  law enforcement high alert following threat co...      1
2  unbelievable obamas attorney general say charl...      1
3  bobby jindal raised hindu us story christian c...      0
4  satan russia unvelis image terrifying new supe...      1
5  time christian group sue amazon splc designati...      1

In [32]:
df.to_csv(r'C:\Users\hp\OneDrive\Documents\Desktop\fake news detection\Data\cleaned_data.csv', index=False)